import javax.swing.*;
import java.awt.*;

public class GUI {
    private JPanel panel;
    private JTabbedPane DeutschTab;
    private JPanel DeutschPanel;
    private JRadioButton Present;
    private JRadioButton Past;
    private JRadioButton Perfect;
    private JRadioButton PastPerfect;
    private JRadioButton Future;
    private JRadioButton Conditional;
    private JRadioButton ich;
    private JRadioButton du;
    private JRadioButton er;
    private JRadioButton wir;
    private JRadioButton ihr;
    private JRadioButton sie;
    private JLabel conjugatedVerb;
    private JButton DeutschConjugateButton;
    private JTextField textField1;

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel = new JPanel();
        panel.setLayout(new GridBagLayout());
        DeutschTab = new JTabbedPane();
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel.add(DeutschTab, gbc);
        DeutschPanel = new JPanel();
        DeutschPanel.setLayout(new GridBagLayout());
        DeutschTab.addTab("DeutschTab", DeutschPanel);
        final JPanel spacer1 = new JPanel();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        DeutschPanel.add(spacer1, gbc);
        Present = new JRadioButton();
        Present.setSelected(true);
        Present.setText("Present");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        DeutschPanel.add(Present, gbc);
        Past = new JRadioButton();
        Past.setText("Past");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        DeutschPanel.add(Past, gbc);
        Perfect = new JRadioButton();
        Perfect.setText("Perfect");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        DeutschPanel.add(Perfect, gbc);
        PastPerfect = new JRadioButton();
        PastPerfect.setText("Past-perfect");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.anchor = GridBagConstraints.WEST;
        DeutschPanel.add(PastPerfect, gbc);
        Future = new JRadioButton();
        Future.setText("Future");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        DeutschPanel.add(Future, gbc);
        Conditional = new JRadioButton();
        Conditional.setText("Conditional");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        DeutschPanel.add(Conditional, gbc);
        ich = new JRadioButton();
        ich.setSelected(true);
        ich.setText("ich");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.anchor = GridBagConstraints.WEST;
        DeutschPanel.add(ich, gbc);
        du = new JRadioButton();
        du.setText("du");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        DeutschPanel.add(du, gbc);
        er = new JRadioButton();
        er.setText("er");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.WEST;
        DeutschPanel.add(er, gbc);
        wir = new JRadioButton();
        wir.setText("wir");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.anchor = GridBagConstraints.WEST;
        DeutschPanel.add(wir, gbc);
        ihr = new JRadioButton();
        ihr.setText("ihr");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 4;
        gbc.anchor = GridBagConstraints.WEST;
        DeutschPanel.add(ihr, gbc);
        sie = new JRadioButton();
        sie.setText("sie");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 5;
        gbc.anchor = GridBagConstraints.WEST;
        DeutschPanel.add(sie, gbc);
        final JToolBar.Separator toolBar$Separator1 = new JToolBar.Separator();
        gbc = new GridBagConstraints();
        gbc.gridx = 3;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        DeutschPanel.add(toolBar$Separator1, gbc);
        conjugatedVerb = new JLabel();
        conjugatedVerb.setAutoscrolls(false);
        conjugatedVerb.setText("");
        gbc = new GridBagConstraints();
        gbc.gridx = 4;
        gbc.gridy = 5;
        gbc.gridwidth = 4;
        gbc.fill = GridBagConstraints.BOTH;
        DeutschPanel.add(conjugatedVerb, gbc);
        DeutschConjugateButton = new JButton();
        DeutschConjugateButton.setRolloverEnabled(false);
        DeutschConjugateButton.setSelected(false);
        DeutschConjugateButton.setText("Konjugier!");
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 3;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        DeutschPanel.add(DeutschConjugateButton, gbc);
        textField1 = new JTextField();
        textField1.setColumns(2);
        textField1.setDragEnabled(false);
        textField1.setPreferredSize(new Dimension(24, 24));
        textField1.putClientProperty("html.disable", Boolean.FALSE);
        gbc = new GridBagConstraints();
        gbc.gridx = 6;
        gbc.gridy = 1;
        gbc.gridwidth = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        DeutschPanel.add(textField1, gbc);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        DeutschTab.addTab("Untitled", panel1);
        ButtonGroup buttonGroup;
        buttonGroup = new ButtonGroup();
        buttonGroup.add(Conditional);
        buttonGroup.add(Conditional);
        buttonGroup.add(Future);
        buttonGroup.add(Past);
        buttonGroup.add(Present);
        buttonGroup.add(Perfect);
        buttonGroup.add(PastPerfect);
        buttonGroup = new ButtonGroup();
        buttonGroup.add(ich);
        buttonGroup.add(ich);
        buttonGroup.add(sie);
        buttonGroup.add(er);
        buttonGroup.add(wir);
        buttonGroup.add(du);
        buttonGroup.add(ihr);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel;
    }

    public static void main(String[] args) {
        JFrame frame = new JFrame("GUI");
        frame.setContentPane(new GUI().panel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }
}
